"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import os

import dj_database_url
from dotenv import load_dotenv


# ============================================================
# ENVIRONMENT
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-local-development-key"
)

DEBUG = os.environ.get(
    "DEBUG",
    "True"
).lower() == "true"


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".onrender.com",
    ".e2b.app",
]


CSRF_TRUSTED_ORIGINS = [
    "https://*.e2b.app",
    "https://*.onrender.com",
]


# Detect E2B / Arena preview environment
IS_PREVIEW = os.environ.get(
    "E2B_SANDBOX",
    ""
).lower() == "true"


# Render / reverse proxy HTTPS
SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)


# ============================================================
# COOKIE SETTINGS
# ============================================================

if not DEBUG:
    # Production
    CSRF_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SECURE = True

    SESSION_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SECURE = True

elif IS_PREVIEW:
    # E2B / Arena preview
    CSRF_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SECURE = False

    SESSION_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SECURE = False

else:
    # Local development
    CSRF_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SECURE = False

    SESSION_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SECURE = False


# ============================================================
# APPLICATION DEFINITION
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",

    # Cloudinary (MUST be before staticfiles)
    "cloudinary_storage",

    # Django static files
    "django.contrib.staticfiles",

    # Main application
    "designer",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise serves static files
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "core.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "core.wsgi.application"


# ============================================================
# DATABASE
# ============================================================

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    # Local SQLite fallback
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATIC_DIR = BASE_DIR / "static"

if STATIC_DIR.exists():
    STATICFILES_DIRS = [
        STATIC_DIR
    ]
else:
    STATICFILES_DIRS = []


# ============================================================
# STORAGE CONFIGURATION
# ============================================================
#
# Uploaded files (media): Cloudinary
# Static files: Django Standard (Served via WhiteNoise Middleware)
#
# ============================================================

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# ============================================================
# CLOUDINARY COMPATIBILITY
# ============================================================

STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"


# ============================================================
# CLOUDINARY CONFIGURATION
# ============================================================

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME", ""),
    "API_KEY": os.environ.get("CLOUDINARY_API_KEY", ""),
    "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET", ""),
}


# ============================================================
# MEDIA / UPLOADED FILES
# ============================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# FILE UPLOAD LIMITS
# ============================================================

MAX_UPLOAD_SIZE = 1024 * 1024 * 1024

FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE

DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE


# ============================================================
# AUTHENTICATION REDIRECTS
# ============================================================

LOGIN_URL = "/login/"

LOGIN_REDIRECT_URL = "/user-dashboard/"

LOGOUT_REDIRECT_URL = "/"


# ============================================================
# AI / GEMINI
# ============================================================

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")

AI_MODEL = os.environ.get("AI_MODEL", "gemini-3.6-flash")

HUGGINGFACE_TOKEN = os.environ.get("HUGGINGFACE_TOKEN", "")


# ============================================================
# OPENAI
# ============================================================

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================
# PRODUCTION SECURITY
# ============================================================

if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "exam-gen-cache",
        }
    }